api_root:
    path: /
    controller: Ynlo\GraphQLBundle\Controller\GraphQLEndpointController
    methods: [POST, OPTIONS]

api_subscriptions:
    path: /subscription/{subscription}
    requirements: { subscription: "^[a-zA-Z0-9-]*$" }
    controller: Ynlo\GraphQLBundle\Controller\SubscriptionsController
    methods: [GET, OPTIONS]

api_subscriptions_heartbeat:
    path: /subscription/{subscription}/heartbeat
    requirements: { subscription: "^[a-zA-Z0-9-]*$" }
    controller: Ynlo\GraphQLBundle\Controller\SubscriptionsHeartbeatController
    methods: [GET, OPTIONS]

api_schema:
    path: /schema.graphql
    controller: Ynlo\GraphQLBundle\Controller\SchemaController
    defaults: { _format: graphql }

api_schema_json:
    path: /schema.json
    controller: Ynlo\GraphQLBundle\Controller\SchemaController
    defaults: { _format: json }
