api_root:
    path:      /
    defaults:  { _controller: Ynlo\GraphQLBundle\Controller\GraphQLEndpointController }

api_schema:
    path:      /schema.graphql
    defaults:  { _controller: Ynlo\GraphQLBundle\Controller\SchemaController }
