api_root:
    path:      /
    defaults:  { _controller: YnloGraphQLBundle:GraphQLEndpoint:root }

api_schema:
    path:      /schema.graphql
    defaults:  { _controller: YnloGraphQLBundle:Schema:schema }