language: php

php:
  - 7.1

env:
  - SYMFONY_DEPRECATIONS_HELPER: weak

cache:
  directories:
    - .composer/cache

before_install:
  - alias composer=composer\ -n && composer self-update

install:
  - travis_retry composer global require hirak/prestissimo
  - travis_retry composer install --no-interaction

script:
  - mkdir -p build/logs
  - php bin/phpunit -c phpunit.xml.dist --coverage-text --coverage-clover=${clover=build/logs/clover.xml}
  - cd demo
  - rm -rf var/cache
  - php ../bin/behat -f progress --rerun --no-interaction
  - cd ..

after_success:
 - composer require satooshi/php-coveralls
 - php bin/coveralls
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --format=php-clover "$clover"
 - cd doc
 - composer install
 - composer build
 - cd ..

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: doc/static
  on:
    branch: master

notifications:
  email:
    - rsantos@ynloultratech.com