language: php

php:
  - 7.1

env:
  - SYMFONY_DEPRECATIONS_HELPER: weak

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: hhvm
  allow_failures:
    - php: hhvm

cache:
  directories:
    - .composer/cache

before_install:
  - alias composer=composer\ -n && composer self-update
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - travis_retry composer global require hirak/prestissimo
  - travis_retry composer install --no-interaction

script:
  - mkdir -p build/logs
  - php bin/phpunit -c phpunit.xml.dist --coverage-text --coverage-clover=${clover=build/logs/clover.xml} > /dev/null

after_success:
 - composer require satooshi/php-coveralls
 - php bin/coveralls
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --format=php-clover "$clover"

notifications:
  email:
    - rsantos@ynloultratech.com