services:
    tagged_services:
        class: Ynlo\GraphQLBundle\Component\TaggedServices\TaggedServices
        arguments: [ '@service_container' ]

    Ynlo\GraphQLBundle\EventListener\CorsListener:
          class: Ynlo\GraphQLBundle\EventListener\CorsListener
          tags:
              - { name: 'kernel.event_subscriber' }

    graphql.schema_compiler:
        class: Ynlo\GraphQLBundle\Definition\SchemaCompiler
        arguments: ['@graphql.definition_registry']
        calls:
          - [ setContainer, ['@service_container']]

    graphql.definition_registry:
        class: Ynlo\GraphQLBundle\DefinitionLoader\DefinitionRegistry
        arguments: ['@tagged_services', '%kernel.cache_dir%']

    graphql.definition_auto_loader:
        class: Ynlo\GraphQLBundle\DefinitionLoader\DefinitionAutoLoader
        arguments: ['@service_container']
        tags:
            - { name: 'graphql.definition_loader' }

    Ynlo\GraphQLBundle\DefinitionLoader\DefinitionResolver\ObjectTypeResolver:
        class: Ynlo\GraphQLBundle\DefinitionLoader\DefinitionResolver\ObjectTypeResolver
        arguments: ['@tagged_services','@graphql.connection_builder']
        calls:
            - [ setReader, ['@annotations.reader']]
        tags:
            - { name: 'graphql.definition_resolver', priority: 200}

    Ynlo\GraphQLBundle\DefinitionLoader\DefinitionResolver\QueryGetNodeResolver:
        class: Ynlo\GraphQLBundle\DefinitionLoader\DefinitionResolver\QueryGetNodeResolver
        calls:
            - [ setReader, ['@annotations.reader']]
        tags:
            - { name: 'graphql.definition_resolver', priority: 150 }

    Ynlo\GraphQLBundle\DefinitionLoader\DefinitionResolver\QueryGetAllNodes:
        class: Ynlo\GraphQLBundle\DefinitionLoader\DefinitionResolver\QueryGetAllNodes
        arguments: ['@graphql.connection_builder']
        calls:
            - [ setReader, ['@annotations.reader']]
        tags:
            - { name: 'graphql.definition_resolver', priority: 150 }

    Ynlo\GraphQLBundle\DefinitionLoader\DefinitionResolver\QueryResolver:
        class: Ynlo\GraphQLBundle\DefinitionLoader\DefinitionResolver\QueryResolver
        arguments: ['@graphql.connection_builder']
        calls:
            - [ setReader, ['@annotations.reader']]
        tags:
            - { name: 'graphql.definition_resolver', priority: 100 }

    Ynlo\GraphQLBundle\DefinitionLoader\DefinitionResolver\MutationDefinitionLoader:
        class: Ynlo\GraphQLBundle\DefinitionLoader\DefinitionResolver\MutationDefinitionLoader
        arguments: ['@form.factory']
        calls:
            - [ setReader, ['@annotations.reader']]
        tags:
            - { name: 'graphql.definition_resolver', priority: 100 }

    Ynlo\GraphQLBundle\DefinitionLoader\DefinitionResolver\MutationAddDefinitionLoader:
        class: Ynlo\GraphQLBundle\DefinitionLoader\DefinitionResolver\MutationAddDefinitionLoader
        arguments: ['@form.factory']
        calls:
            - [ setReader, ['@annotations.reader']]
        tags:
            - { name: 'graphql.definition_resolver', priority: 100 }

    Ynlo\GraphQLBundle\DefinitionLoader\DefinitionResolver\MutationUpdateDefinitionLoader:
        class: Ynlo\GraphQLBundle\DefinitionLoader\DefinitionResolver\MutationUpdateDefinitionLoader
        arguments: ['@form.factory']
        calls:
            - [ setReader, ['@annotations.reader']]
        tags:
            - { name: 'graphql.definition_resolver', priority: 100 }

    Ynlo\GraphQLBundle\DefinitionLoader\DefinitionResolver\MutationDeleteDefinitionLoader:
        arguments: ['@form.factory']
        calls:
            - [ setReader, ['@annotations.reader']]
        tags:
            - { name: 'graphql.definition_resolver', priority: 100 }

    Ynlo\GraphQLBundle\DefinitionLoader\DefinitionResolver\QueryFieldResolver:
        class: Ynlo\GraphQLBundle\DefinitionLoader\DefinitionResolver\QueryFieldResolver
        arguments: ['@graphql.connection_builder']
        calls:
            - [ setReader, ['@annotations.reader']]
        tags:
            - { name: 'graphql.definition_resolver', priority: 50 }

    Ynlo\GraphQLBundle\DefinitionLoader\DefinitionResolver\FieldDecorator\GraphQLFieldDefinitionDecorator:
        class: Ynlo\GraphQLBundle\DefinitionLoader\DefinitionResolver\FieldDecorator\GraphQLFieldDefinitionDecorator
        calls:
            - [ setReader, ['@annotations.reader']]
        tags:
            - { name: 'graphql.field_definition_decorator', priority: 100 }

    Ynlo\GraphQLBundle\DefinitionLoader\DefinitionResolver\FieldDecorator\DoctrineFieldDefinitionDecorator:
        class: Ynlo\GraphQLBundle\DefinitionLoader\DefinitionResolver\FieldDecorator\DoctrineFieldDefinitionDecorator
        arguments: ['@tagged_services']
        calls:
            - [ setReader, ['@annotations.reader']]
        tags:
            - { name: 'graphql.field_definition_decorator' }

    graphql.connection_builder:
        class: Ynlo\GraphQLBundle\Definition\ConnectionDefinitionBuilder
        arguments: ['@graphql.definition_registry']
        shared: false

    graphql.types_autoloader:
        class: Ynlo\GraphQLBundle\Type\TypeAutoLoader
        calls:
          - [ setContainer, ['@service_container']]

    Ynlo\GraphQLBundle\Form\TypeGuesser\GraphQLIDTypeGuesser:
        arguments: ['@annotations.reader']
        tags: [form.type_guesser]

    Ynlo\GraphQLBundle\Form\Type\IDType:
        arguments: ['@Doctrine\ORM\EntityManagerInterface', '@graphql.definition_registry']
        tags: [form.type]