services:
    Ynlo\GraphQLBundle\Component\TaggedServices\TaggedServices:
        arguments: [ '@service_container' ]

    Ynlo\GraphQLBundle\EventListener\CorsListener:
        tags:
          - { name: 'kernel.event_subscriber' }

    Ynlo\GraphQLBundle\Schema\SchemaCompiler:
        arguments: ['@Ynlo\GraphQLBundle\Definition\Registry\DefinitionRegistry']
        calls:
          - [ setContainer, ['@service_container']]

    Ynlo\GraphQLBundle\Definition\Registry\DefinitionRegistry:
        arguments: ['@Ynlo\GraphQLBundle\Component\TaggedServices\TaggedServices', '%kernel.cache_dir%', '%graphql.config%']

    Ynlo\GraphQLBundle\Definition\Loader\AnnotationLoader:
        arguments: ['@service_container']
        tags:
            - { name: 'graphql.definition_loader' }

    Ynlo\GraphQLBundle\Definition\Loader\Annotation\ObjectTypeAnnotationParser:
        arguments: ['@Ynlo\GraphQLBundle\Component\TaggedServices\TaggedServices', '@Ynlo\GraphQLBundle\Extension\ExtensionManager']
        calls:
            - [ setReader, ['@annotations.reader']]
        tags:
            - { name: 'graphql.definition_resolver', priority: 200}

    Ynlo\GraphQLBundle\Definition\Loader\Annotation\QueryGetNodeAnnotationParser:
        arguments: ['@Ynlo\GraphQLBundle\Extension\ExtensionManager']
        calls:
            - [ setReader, ['@annotations.reader']]
        tags:
            - { name: 'graphql.definition_resolver', priority: 150 }

    Ynlo\GraphQLBundle\Definition\Loader\Annotation\QueryGetAllNodesAnnotationParser:
        arguments: [ '@Ynlo\GraphQLBundle\Extension\ExtensionManager']
        calls:
            - [ setReader, ['@annotations.reader']]
        tags:
            - { name: 'graphql.definition_resolver', priority: 150 }

    Ynlo\GraphQLBundle\Definition\Loader\Annotation\QueryAnnotationParser:
        arguments: ['@Ynlo\GraphQLBundle\Extension\ExtensionManager']
        calls:
            - [ setReader, ['@annotations.reader']]
        tags:
            - { name: 'graphql.definition_resolver', priority: 100 }

    Ynlo\GraphQLBundle\Definition\Loader\Annotation\MutationAnnotationParser:
        arguments: ['@form.factory','@Ynlo\GraphQLBundle\Extension\ExtensionManager']
        calls:
            - [ setReader, ['@annotations.reader']]
        tags:
            - { name: 'graphql.definition_resolver', priority: 100 }

    Ynlo\GraphQLBundle\Definition\Loader\Annotation\MutationAddAnnotationParser:
        arguments: ['@form.factory','@Ynlo\GraphQLBundle\Extension\ExtensionManager']
        calls:
            - [ setReader, ['@annotations.reader']]
        tags:
            - { name: 'graphql.definition_resolver', priority: 100 }

    Ynlo\GraphQLBundle\Definition\Loader\Annotation\MutationUpdateAnnotationParser:
        arguments: ['@form.factory','@Ynlo\GraphQLBundle\Extension\ExtensionManager']
        calls:
            - [ setReader, ['@annotations.reader']]
        tags:
            - { name: 'graphql.definition_resolver', priority: 100 }

    Ynlo\GraphQLBundle\Definition\Loader\Annotation\MutationDeleteAnnotationParser:
        arguments: ['@form.factory','@Ynlo\GraphQLBundle\Extension\ExtensionManager']
        calls:
            - [ setReader, ['@annotations.reader']]
        tags:
            - { name: 'graphql.definition_resolver', priority: 100 }

    Ynlo\GraphQLBundle\Definition\Loader\Annotation\FieldConnectionAnnotationParser:
        arguments: ['@Ynlo\GraphQLBundle\Extension\ExtensionManager']
        calls:
            - [ setReader, ['@annotations.reader']]
        tags:
            - { name: 'graphql.definition_resolver', priority: 50 }

    Ynlo\GraphQLBundle\Definition\Loader\Annotation\FieldDecorator\GraphQLFieldDefinitionDecorator:
        calls:
            - [ setReader, ['@annotations.reader']]
        tags:
            - { name: 'graphql.field_definition_decorator', priority: 100 }

    Ynlo\GraphQLBundle\Definition\Loader\Annotation\FieldDecorator\DoctrineFieldDefinitionDecorator:
        arguments: ['@Ynlo\GraphQLBundle\Component\TaggedServices\TaggedServices']
        calls:
            - [ setReader, ['@annotations.reader']]
        tags:
            - { name: 'graphql.field_definition_decorator' }

    Ynlo\GraphQLBundle\Type\TypeAutoLoader:
        calls:
          - [ setContainer, ['@service_container']]

    Ynlo\GraphQLBundle\Form\TypeGuesser\GraphQLIDTypeGuesser:
        arguments: ['@annotations.reader']
        tags: [form.type_guesser]

    Ynlo\GraphQLBundle\Form\TypeGuesser\GraphQLEnumTypeGuesser:
        arguments: ['@annotations.reader']
        tags: [form.type_guesser]

    Ynlo\GraphQLBundle\Form\Type\IDType:
        arguments: ['@Doctrine\ORM\EntityManagerInterface', '@Ynlo\GraphQLBundle\Definition\Registry\DefinitionRegistry']
        tags: [form.type]

    Ynlo\GraphQLBundle\Extension\ExtensionManager:
        arguments: ['@Ynlo\GraphQLBundle\Component\TaggedServices\TaggedServices']

    Ynlo\GraphQLBundle\Extension\PaginationExtension:
        arguments: ['@annotations.reader','%graphql.pagination%']
        tags:
          - { name: 'graphql.extension'}

    Ynlo\GraphQLBundle\Extension\NamespaceDefinitionParserExtension:
        arguments: ['@annotations.reader', '%graphql.schema_namespaces%']
        tags:
          - { name: 'graphql.extension'}
