imports:
    - { resource: "transformers.yml" }
    - { resource: "preprocessors.yml" }

parameters:
    graphql.contexts:
        - Ynlo\GraphQLBundle\Behat\Context\AssertContext
        - Ynlo\GraphQLBundle\Behat\Context\DatabaseContext
        - Ynlo\GraphQLBundle\Behat\Context\DoctrineContext
        - Ynlo\GraphQLBundle\Behat\Context\GraphQLContext
        - Ynlo\GraphQLBundle\Behat\Context\ResponseContext
        - Ynlo\GraphQLBundle\Behat\Context\StorageContext
        - Ynlo\GraphQLBundle\Behat\Context\JWTContext
        - Ynlo\GraphQLBundle\Behat\Context\RouteContext
        - Ynlo\GraphQLBundle\Behat\Context\SchemaSnapshotContext

services:
  Ynlo\GraphQLBundle\Behat\Fixtures\FixtureManager:
    arguments:
      - '@fob_symfony.kernel'

  Ynlo\GraphQLBundle\Behat\Fixtures\LoadFixturesSubscriber:
    arguments:
      - '@fob_symfony.kernel'
      - '@Ynlo\GraphQLBundle\Behat\Fixtures\FixtureManager'
    tags:
      - { name: 'event_dispatcher.subscriber' }

  Ynlo\GraphQLBundle\Behat\Client\GraphQLClient:
    arguments:
      - '@fob_symfony.kernel'
      - '@Ynlo\GraphQLBundle\Behat\Deprecation\DeprecationAdviser'
      - '%graphql.client_config%'

  Ynlo\GraphQLBundle\Behat\Client\ClientResetSubscriber:
    arguments:
      - '@Ynlo\GraphQLBundle\Behat\Client\GraphQLClient'
    tags:
      - { name: 'event_dispatcher.subscriber' }

  Ynlo\GraphQLBundle\Behat\Client\ClientAwareInitializer:
    arguments:
      - '@Ynlo\GraphQLBundle\Behat\Client\GraphQLClient'
    tags: ['context.initializer']

  Ynlo\GraphQLBundle\Behat\Kernel\KernelAwareInitializer:
    arguments:
      - '@fob_symfony.kernel'
    tags: ['context.initializer']

  Ynlo\GraphQLBundle\Behat\Storage\Storage: ~

  Ynlo\GraphQLBundle\Behat\Storage\StorageResetSubscriber:
    arguments:
      - '@Ynlo\GraphQLBundle\Behat\Storage\Storage'
    tags:
      - { name: 'event_dispatcher.subscriber' }

  Ynlo\GraphQLBundle\Behat\Storage\StorageAwareInitializer:
    arguments:
      - '@Ynlo\GraphQLBundle\Behat\Storage\Storage'
    tags: ['context.initializer']

  Ynlo\GraphQLBundle\Behat\Deprecation\DeprecationAdviser:
    tags:
        - { name: 'event_dispatcher.subscriber' }
