api:
      resource: '@YnloGraphQLBundle/Resources/config/routing/root.yml'
      prefix:   /

api_explore:
      resource: '@YnloGraphQLBundle/Resources/config/routing/explorer.yml'
      prefix:   /explorer

api_login:
      path: login
      defaults:
          _format: json