services:
    Ynlo\GraphQLBundle\Demo\AppBundle\EventListener\Doctrine\TimestampableSubscriber:
        public: false
        tags: ['doctrine.event_subscriber']

    Ynlo\GraphQLBundle\Demo\AppBundle\Query\User\Field\isCurrent:
        public: true
        arguments: ['@security.token_storage']



